swagger: '2.0'
info:
  title: JWT
  x-ibm-name: jwt
  version: 1.0.0
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - set-variable:
          version: 2.0.0
          title: set-variable
          actions:
            - set: hs256-key
              value: >-
                { "alg": "HS256", "kty": "oct", "use": "sig", "k":
                "o5yErLaE-dbgVpSw65Rq57OA9dHyaF66Q_Et5azPa-XUjbyP0w9iRWhR4kru09aFfQLXeIODIN4uhjElYKXt8n76jt0Pjkd2pqk4t9abRF6tnL19GV4pflfL6uvVKkP4weOh39tqHt4TmkBgF2P-gFhgssZpjwq6l82fz3dUhQ2nkzoLA_CnyDGLZLd7SZ1yv73uzfE2Ot813zmig8KTMEMWVcWSDvy61F06vs_6LURcq_IEEevUiubBxG5S2akNnWigfpbhWYjMI5M22FOCpdcDBt4L7K1-yHt95Siz0QUb0MNlT_X8F76wH7_A37GpKKJGqeaiNWmHkgWdE8QWDQ",
                "kid": "hs256-key" }
              type: string
      - switch:
          version: 2.1.0
          title: switch
          case:
            - condition: $apiCtx().request.path = '/jwt/generate'
              execute:
                - jwt-generate:
                    version: 2.0.0
                    title: jwt-generate
                    jwt: generated.jwt
                    iss-claim: request.headers.iss-claim
                    exp-claim: 3600
                    jti-claim: false
                    sub-claim: ''
                    aud-claim: request.headers.aud-claim
                    jws-jwk: hs256-key
                    jws-alg: HS256
                - gatewayscript:
                    version: 2.0.0
                    title: gatewayscript
                    source: "var apim = require('apim');\r\napim.setvariable('message.body',apim.getvariable('generated.jwt'));"
            - condition: $apiCtx().request.path = '/jwt/validate'
              execute:
                - jwt-validate:
                    version: 2.0.0
                    title: jwt-validate
                    jwt: request.headers.authorization
                    output-claims: decoded.claims
                    jws-jwk: hs256-key
                - gatewayscript:
                    version: 2.0.0
                    title: gatewayscript
                    source: "var apim = require('apim');\r\napim.setvariable('message.body',apim.getvariable('decoded.claims'));"
    catch:
      - default:
          - gatewayscript:
              version: 2.0.0
              title: gatewayscript
              source: "var apim = require('apim');\r\napim.setvariable('message.body',apim.getvariable('jwt-validate.error-message'));"
          - throw:
              version: 2.1.0
              title: throw
              name: invalid JWT token
              error-status-code: '403'
              error-status-reason: Forbidden
              message: invalid JWT token
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
basePath: /jwt
paths:
  /validate:
    get:
      responses:
        '200':
          description: success OK
          schema:
            type: string
      produces: []
    parameters:
      - name: Authorization
        required: true
        in: header
        type: string
        description: Bearer [JWT TOKEN]
  /generate:
    get:
      responses:
        '200':
          description: success OK
          schema:
            type: string
      parameters: []
      schemes: []
    parameters:
      - name: iss-claim
        required: true
        in: header
        type: string
        description: https://myidp.ibm.com
      - name: aud-claim
        required: true
        in: header
        type: string
        description: ClientID1
securityDefinitions: {}
schemes:
  - https
produces: []
responses: {}
